### ISSUE TITLE
How does this apply to general signals?

### ISSUE THREAD

**Issue by shaperilio** [aewallin/allantools#121]
The example from Analog Devices [here](https://ez.analog.com/mems/w/documents/4509/faq-gyroscope-angle-random-walk) gives the following value for the deviation with tau = 1 second (after you fix the slight mistakes in their spreadsheet):

`0.004 878 48`

Following the description [here](https://www.phidgets.com/docs/Allan_Deviation_Primer), I implemented my own version. This description is very simple: "the Allan Deviation for tau = 1 second is the standard deviation of the averages of the signal every 1 second" (there are 30 such periods in this dataset). I compute:

`0.004 954 74`

Which is "close".

If I call `(taus, adev, _, ns) = allantools.adev(data, rate_Hz, taus=1)` with `rate_Hz = 10`, I get:

`0.031 938 69`

Which is "not even close".

This equation from [Wikipedia](https://en.wikipedia.org/wiki/Allan_variance#Allan_variance) is perplexing me:

![image](https://user-images.githubusercontent.com/26465923/81030794-f2bfe400-8e3e-11ea-923b-d996ab5cdb02.png)

Your implementaiton of `adev` seems to be the right side, with `x`; the spreadsheet uses the version with `y_bar`, where, according to them, `y_bar = mean x for each subperiod of length tau`, which is most definitely not algebraically equivalent to what you've implemented. The "verbal" version I implemented is not algebraically equivalent to either.

I understand, as usual, that different people call things by different names (the spreadsheet refers to "variance" when they mean "deviation"), but what gives? What is the general application of this library to a sampled signal?

**Comment by aewallin** [comment]
When ADEV is used for time/frequency data the x-formula and y-formula are equivalent, because fractional frequency y is the time derivative of phase x.

When ADEV is (mis)used for other raw data input like voltage (or like above, acceleration?), you most probably want to treat it like (fractional) frequency data and use the y-formula.
this is done in allantools with the **data_type='freq'** argument.

The AD-website link talks about 30s averages - allantools does the averaging for you. feed the raw data (e.g. sampled at 10S/s), and if you want ADEV at both tau=1s and tau=30s, with rate=10(Hz), then call with taus=[1,30]

**Comment by shaperilio** [comment]
Thanks for the clarification!
