### ISSUE TITLE
ci_demo.py parameter mistake 

### ISSUE THREAD

**Issue by canvaskan** [aewallin/allantools#125]
In ci_demo.py 
```python

# Confidence-intervals for each (tau,adev) pair separately.
cis=[]
for (t,dev) in zip(taus,devs):
    # Greenhalls EDF (Equivalent Degrees of Freedom)
    # alpha     +2,...,-4   noise type, either estimated or known
    # d         1 first-difference variance, 2 allan variance, 3 hadamard variance
    #           we require: alpha+2*d >1     (is this ever false?)
    #!!!NOTE1: # m         tau/tau0 averaging factor                                                                                                      
    # N         number of phase observations
    #!!!NOTE2edf = at.edf_greenhall( alpha=0, d=2, m=t, N=len(phase), overlapping = False, modified=False )     
    # with the known EDF we get CIs 
    (lo,hi) = at.confidence_interval( dev=dev,  edf=edf )
    cis.append( (lo,hi) )

````
According to !!!NOTE1:m is  tau/tau0 averaging factor , so maybe at !!!NOTE2 it should be m = t/tau0 ?
That is #!!!NOTE2edf = at.edf_greenhall( alpha=0, d=2, m=t/tau0, N=len(phase), overlapping = False, modified=False )    
as I tested it on my own data and compared with other software's results

**Comment by aewallin** [comment]
Thanks for the comment. This issue is probably because when tau0=1s, there is no difference between the value of tau and that of m=tau/tau0.

The documentation of edf_greenhall() should be OK however?
https://allantools.readthedocs.io/en/latest/functions.html#allantools.edf_greenhall

If there are other documentation issues let me know - otherwise closing this in a few days.

**Comment by canvaskan** [comment]
No other issues. The documentation of edf_greenhall() is right. Thank you for your work!
