### ISSUE TITLE
Change license to LGPL v3 or later

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#65]
I have received a request for changing the license of AllanTools from GPL to LGPL to allow for more flexible integration of the library into e.g. monitoring-dashboards for time/frequency fiber-links.

The license change can be discussed below - or you can simply reply "ok" or "yes" if you do not see any problems with the license change.

I will implement the license change in about one week starting Monday 2018-03-26 and follow that with a new release - unless there are issues emerging here that should be handled first.

**Comment by fmeynadier** [comment]
TL;DR: ok

I remember a possible switch to BSD has been discussed in order to integrate some code in scipy (circa 1 year ago) but the discussion quickly stopped and the proposition did not seem to have strong support, so I assume today’s choice is independent from that.

And like one year ago, I have no strong opinion on this subject and will support whatever option you choose.

**Comment by telegraphic** [comment]
Hi, Yes, I am amenable to relicensing under any more permissive license, including LGPL / BSD / MIT.

**Comment by aewallin** [comment]
Thanks for the comments.
I will commit changes towards LGPL v3 or later starting today Monday 2018-03-26 with the goal of a new release at the end of the week. Pull requests are ofcourse welcome as usual ;)

**Comment by aewallin** [comment]
The license has been changed. closing this issue.
